apiVersion: v1
kind: Pod
metadata:
  labels:
    run: meupod
    service: webserver
  name: meupod
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
