apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-girus
    opa: sensacional-juvenal
name: nginx-girus
specs:
  replicas: 5
    selector:
      matchLabels:
      app: nginx-girus
  strategies:
    type: recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  strategies: {}
  replicas: 2
  template:
    metadata:
    label:
      app: nginx
    specs:
      containers:
      - image: nginx 1.16.0
        name: nginx
        resource: 
          limits:
            cpu: 0.7
            memory: 128Mi
          requests:
            cpu: 0.5
            memory: 64Mi
